### PR TITLE
Issue #84 Enhancement: Implement Search suggestion

### PR DESCRIPTION
**Pull request by mani8177**
@doneill Please review the fix for issue #84

### CODE REVIEW

**Comment by mani8177** [comment]
@doneill Please review the refactored search suggestion using `suggest` method instead of `AsyncTask`

**Comment by mani8177** [comment]
@doneill Please review the PR : Refactored to reduce the delay in suggestions

**Comment by mani8177** [comment]
@doneill Please review the PR

**Comment by doneill** [comment]
@mani8177 Your updates look good, but they have introduced a crash when finding a new route after finding a route from **My Location** to a successful suggestion search result.  

To reproduce: 
1. Do a POI search, e.g. Known stadium or airport, nearby your location 
2. Route from your location to search result from above
3. Clear route
4. Tap the Route button to route between 2 locations
5. Replace **My Location**  with your POI search text from above
6. Pick a new POI search item **To** location
7. Tap the **Get Route** button.

This does not happen if you do steps 4 - 7 w/o first searching for a POI with suggestions. 

The first thing that needs to happen is we need to check for a valid ```RouteResult``` in ```RouteAsyncTask.onPostExecute()``` which will catch this.  Then investigate why we don't get a successful ```RouteResult``` when going through the reproducible workflow.

**Pull request merged**
