### PR TITLE
Fixed compass behavior.

### PR DESCRIPTION
**Pull request by zinfin**
Took Jeff’s suggestions and applied a compass fix.

### CODE REVIEW

**Comment by doneill** [comment]
@zinfin What is to be expected with this fix?  My experience below:  

- When rotating the map I do not see the compass appear.
- After selecting the Locator FAB the compass appears and orientates when rotating the map, but upon clicking the FAB the compass disappears but the map does not orientate to north.

**Comment by zinfin** [comment]
@doneill  I think we need to document what our expectations are for the app.  Here's what I know so far:

- Selecting the locator FAB should display the compass.  I currently observe this behavior.
- Selecting the locator FAB again (when the compass is displayed) should orient the map to the north.  I can confirm the app behaves this way.
- When the compass is shown in the map, it should orient with the map (e.g. the red north arrow should always point to north on the map).  I can also confirm that this works as expected.
- When the compass is shown, tapping it will make it disappear.  This works as expected.
- When the compass disappears, the FAB icon should change from ic_action_compass_mode to ic_menu_my_location.  This currently not happening.

Before making any more changes, let's come to a consensus on the expected behavior and document it in the README.  Can you add any more expected behaviors to this list?

**Comment by doneill** [comment]
@zinfin Here are the expected behaviors of the location button interacting with the compass.  

Compass:
- Whenever the map is not orientated North (non-zero bearing) the compass appears
- When the compass is clicked, the map orients back to north (zero bearing), the default orientation and the compass fades away, or after a short duration disappears. 

Location FAB: 
- Tapping on location button should switch between `NAVIGATION ` & `OFF ` (default)
- When in `NAVIGATION ` mode orientation should be with respect to device. 
- When in 'OFF' mode orientation should return to North.

**Comment by zinfin** [comment]
@doneill 
When in NAVIGATION mode, what does "orientation should be with respect to device" mean?

**Comment by zinfin** [comment]
@doneill I've put in some fixes to align with the desired behavior of the compass and FAB.

**Comment by zinfin** [comment]
@doneill Ready for your review.  Note that mapView.setRotation() isn't working, see line 529 in MapFragment.  When the compass is clicked, the map "should" orient to north but the setRotation() method on the map isn't responding.  This may be a bug with the SDK, I wanted your opinion before filing it.

**Comment by doneill** [comment]
@zinfin I see the issue with `MapView.setRotation()` which comes from Android `View`, try `MapView.setViewpointRotationAsync(0)` to animate the return to North bearing.

**Comment by zinfin** [comment]
@doneill Thanks for the tip Dan.  It's working with the fix you suggested.

**Comment by doneill** [comment]
@zinfin Looks good, merging.

**Comment by doneill** [comment]
This is a fix for #124

**Pull request merged**
